# 数据库配置
database:
  database: sqlite.db
# 日志级别
logger:
  level: DEBUG
auth:
  username: admin
  password: 123456
  jwtSecret: aaabbbccc
  expireMinutes: 120 # 过期时间按照1分钟算
plugin:
  libPath: ./target/debug
server:
  port: 30012