name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release

      - name: Archive artifacts
        run: |
          if ("${{ matrix.os }}" -eq "windows-latest") {
            Compress-Archive -Path "target/release" -DestinationPath "artifacts.zip" -Force
          }
          else {
            tar -czvf artifacts.tar.gz target/release
          }
          Get-FileHash artifacts.* | Format-List | Out-File -FilePath "sha256sum.txt"

          if ("${{ matrix.os }}" -eq "ubuntu-latest") {
            cargo build --release --target=armv7-unknown-linux-gnueabihf
            tar -czvf artifacts-arm.tar.gz target/armv7-unknown-linux-gnueabihf/release
            Get-FileHash artifacts-arm.* | Format-List | Out-File -Append -FilePath "sha256sum.txt"
          }

        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-package
          path: |
            artifacts.zip
            artifacts.tar.gz
            artifacts-arm.tar.gz
            sha256sum.txt
